// AUTO-GENERATED by scripts/build-blog-index.mjs
// DO NOT EDIT — regenerate via "npm run blog-index" ou "npm run build".

export interface BlogFrontmatter {
  title: string;
  slug: string;
  description: string;
  date: string; // ISO (YYYY-MM-DD)
  author: string;
  category: string;
  tags: string[];
  reading_time: number;
  og_image: string;
}

export interface BlogPost {
  slug: string;
  frontmatter: BlogFrontmatter;
  html: string;
}

export const blogPosts: BlogPost[] = [];
